; ENTRY POINT FROM GRUB AND THE C KERNEL IN ASSEMBLY FOR THE "BaseKernel" X86 OPERATING SYSTEM FROM SCRATCH - https://github.com/Huguini79/BaseKernel

BITS 32 ; DEFINE THE BITS (32 BITS)

SECTION .TEXT ; DEFINE TEXT THE SECTION (FOR THE REST OF THE CODE)

; DEFINE THE MULTIBOOT HEADERS
ALIGN 4
DD 0X1BADB002
DD 0X00
DD - (0X1BADB002 + 0X00)

GLOBAL START ; START OF THE KERNEL (ESSENTIAL FOR THE LINKER)
EXTERN kernel_main ; OUR C FUNCTIONS THAT JUMPS TO THE C KERNEL

START:
	CLI ; DISABLE INTERRUPTS
	CALL kernel_main ; JUMP INTO THE C KERNEL
	HLT ; PUT THE DISK IN STANDBY MODE

SECTION .BSS ; DEFINE THE BSS SECTION (FOR THE STACK)

STACK_SPACE: RESB 65536 ; 64 KB OF STACK
